export const mylist = [
	{
		id: "evner",
		firstName: "Ali",
		lastName: "Baba",
		email: "gush@alibaba.com",
		phone: "451346987",
	},
	{
		id: "fbejnokne",
		firstName: "Yossi",
		lastName: "Baba",
		email: "gush@alibaba.com",
		phone: "451346987",
	},
	{
		id: "evner1",
		firstName: "Ali",
		lastName: "Baba",
		// email: "gush@alibaba.com",
		// phone: "451346987",
	},
	{
		id: "fbejnoknww",
		firstName: "Bob",
		lastName: "Baba",
		// email: "gush@alibaba.com",
		phone: "451346987",
	},
	{
		id: "evner11",
		firstName: "Ali",
		lastName: "Baba",
		email: "gush@alibaba.com",
		// phone: "451346987",
	},
	{
		id: "fbejnoknw",
		firstName: "Ali",
		lastName: "Baba",
		// email: "gush@alibaba.com",
		// phone: "451346987",
	},
	{
		id: "evner2",
		firstName: "Ali",
		lastName: "Baba",
		email: "gush@alibaba.com",
		phone: "451346987",
	},
	{
		id: "fbejnokn22",
		firstName: "Yaffa",
		lastName: "Baba",
		// email: "gush@alibaba.com",
		// phone: "451346987",
	},
	{
		id: "evner22",
		firstName: "Ali",
		lastName: "Baba",
		email: "gush@alibaba.com",
		phone: "451346987",
	},
	{
		id: "fbejnokn2",
		firstName: "Ali",
		lastName: "Baba",
		// email: "gush@alibaba.com",
		phone: "451346987",
	},
]